---
title: "Appendix A"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, setup, include=FALSE}
require(mosaic)   # Load additional packages here 
require(xlsx)
require(dplyr)
require(tidyr)
require(randomForest)

# Some customization.  You can alter or delete as desired (if you know what you are doing).
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
```

## Required Packages

```{r, eval = FALSE}
require(mosaic)
require(xlsx)
require(dplyr)
require(tidyr)
require(randomForest)
require(ggplot2)
require(grid)
require(gridExtra)
```

## Loading and cleaning the data

```{r, eval = FALSE}
data <- read.csv("pimaData.csv")
data <- filter(data, Plasma>0, BP>0, BMI>0)
data <- data[-c(1)]
```

## Creating and graphing a random forest

```{r, eval = FALSE}
rf <- randomForest(Diabetic~., data=data)
# Note that the four most predictive variables are 
  # Plasma, BMI, Age, and Pedigree (in that order)
varImpPlot(rf) 
```

## Creating the graph displayed in Section II

```{r, eval = FALSE}
data0 <- filter(data, Diabetic == 1)
data0$Diabetic <- ifelse(data0$Diabetic == 1, "Diabetic", "Not Diabetic")

data1 <- filter(data, Diabetic == 0)
data1$Diabetic <- ifelse(data1$Diabetic == 1, "Diabetic", "Not Diabetic")

g1 <- ggplot(data0, aes(x = Plasma, y = BMI)) + geom_point() + 
  facet_wrap(~Diabetic) + geom_hline(yintercept = mean(data0$BMI), 
                                     color = "red") + 
  geom_vline(xintercept = mean(data0$Plasma), color = "green") +
  geom_text(aes(0, mean(data0$BMI), label = "Average BMI = 35.3", 
                vjust = 1.5, hjust = .1), size = 3) +
  geom_text(aes(mean(data0$Plasma), 0, label = "Average Plasma = 142.6", 
                hjust = 1.1), size = 3) +
  scale_x_continuous(limits = c(0, 200)) + 
  scale_y_continuous(limits = c(0, 70))

g2 <- ggplot(data1, aes(x = Plasma, y = BMI)) + geom_point() + 
  facet_wrap(~Diabetic) + geom_hline(yintercept = mean(data1$BMI), 
                                     color = "red", label) + 
  geom_vline(xintercept = mean(data1$Plasma), color = "green") +
  geom_text(aes(0, mean(data1$BMI), label = "Average BMI = 30.9", 
                vjust = 1.5, hjust = .1), size = 3) +
  geom_text(aes(mean(data1$Plasma), 0, label = "Average Plasma = 111.0", 
                hjust = 1.1), size = 3) +
  scale_x_continuous(limits = c(0, 200)) + 
  scale_y_continuous(limits = c(0, 70))

grid.arrange(g1, g2, ncol = 2, top = "Figure 1. Comparing Averages between 
             Diabetics and Non-Diabetics")
```

## Creating the model shown in Section III

```{r, eval = FALSE}
#randomly divide the observations into a training and test set with a standard 66% split
train_sample <- sample(nrow(data), size=0.66*nrow(data))
#create the training set
train <- data[train_sample,]
#create the test set
test <- data[-train_sample,]

#fit a logit model on the training set using 4 predictors
glm_fit <- glm(Diabetic ~ Plasma+BMI+Age+Pedigree, data = train, family="binomial"(link = "logit"))
#get a summary of the model
summary(glm_fit)
#obtain the exponentiated values of the logit coefficients,
#since they represent the relative risk ratios 
#which allow an easier interpretation of the logit coefficients
exp(coef(glm_fit))

#obtain predicted probabilities of diabetes in our test set
glm_probs <- predict(glm_fit, test, type="response")
#create a vector of class predictions of 247 elements of "0" 
#(0 means no diabetes; 1 means diabetes; 247 is number of observations in the test set)
glm_pred <- rep("0", 247)
#transforms to "1" all of the elements for which the predicted probability of diabetes exceeds 0.5
glm_pred[glm_probs>.5] <- "1"
#given these predictions, produce a confusion matrix 
table(glm_pred, test$Diabetic)
#compute the accuracy rate of the logistic model
mean(glm_pred==test$Diabetic)
```

## Creating the graph shown in Section III

```{r, eval = FALSE}
#create logistic curves of probabilities of diabetes based on Plasma, BMI, Age, Pedigree
par(mfrow=c(2,2))
logi.hist.plot(data$Plasma, data$Diabetic, logi.mod=1, type="hist", 
               boxp=FALSE, rug=FALSE, ylabel="Probability of Diabetic",
               ylabel2="Frequency of Plasma", xlabel="Plasma", 
               mainlabel="Probability of Diabetes Based on Plasma Glucose")
logi.hist.plot(data$BMI, data$Diabetic, logi.mod=1, type="hist", 
               boxp=FALSE, rug=FALSE, ylabel="Probability of Diabetic",
               ylabel2="Frequency of BMI", xlabel="BMI", 
               mainlabel="Probability of Diabetes Based on Body Mass Index")
logi.hist.plot(data$Age, data$Diabetic, logi.mod=1, type="hist", 
               boxp=FALSE, rug=FALSE, ylabel="Probability of Diabetic",
               ylabel2="Frequency of Age", xlabel="Age", 
               mainlabel="Probability of Diabetes Based on Age")
logi.hist.plot(data$Pedigree, data$Diabetic, logi.mod=1, type="hist", 
               boxp=FALSE, rug=FALSE, ylabel="Probability of Diabetic",
               ylabel2="Frequency of Pedigree", xlabel="Pedigree", 
               mainlabel="Probability of Diabetes Based on Pedigree Function")
```